define(["dojo", "put-selector/put", "dojo/date"], 
function(dojo, put, DD) {


  /* 
   Lifecycle refresher:
   
   new EventGrid:
    preamble
    constructor
    postscript
  */

   var genId = 1;
   function nextId() {
     return "event_grid_" + genId++;
   }
  
  return dojo.declare([], {
    showData: null,
    
    constructor: function(opts, srcNodeRef) {
      console.debug("CTOR");
    },
    
    postscript: function(opts, srcNodeRef) {
      console.debug("POSTSCRIPT");
      if (srcNodeRef) {
				// normalize srcNodeRef and store on instance during create process.
				this.srcNodeRef = srcNodeRef = srcNodeRef.nodeType ? srcNodeRef : dojo.byId(srcNodeRef);
			} 
      this.create(opts, srcNodeRef)
      this.inherited(arguments);
    },
    
    preamble: function() {
      this.inherited(arguments);
      console.debug("PREAMBLE");
    },

    // =====
    
    create: function(opts, srcNodeRef) {

      this.showData = opts.showData;

      var domNode = srcNodeRef || put("div");
      this.domNode = domNode;
      
      // apply id to widget and domNode. From incoming node, widget params, or autogenerated.
    	this.id = domNode.id = domNode.id || this.id || nextId();
      
      put(domNode, '.event-grid');
      this.render();
    },
    
    render: function() {
      this.headerNode = put(this.domNode, 'div.egrid-header');
      this.bodyNode = put(this.domNode, 'div.egrid-body');
      
      var table = put(this.domNode, 'table tbody');
      this.headerNode = put(table, 'tr.egrid-header');
      this.bodyNode = put(table, 'tr.egrid-body');
      this.footerNode = put(table, 'tr.egrid-footer');

      this.renderHeader();
      
      this.renderBody();
    },
    
    renderHeader: function() {
      console.debug("this. = %o", this);
      put(this.headerNode, 'th'); // no header content for times column
      // dojo.forEach(['Stage One', 'Stage Two', 'Stage Three'], function(stageName) {
      //   put(this.headerNode, 'th $', stageName);
      // }, this);

      dojo.forEach(this.showData, function(showsInfo) {
        put(this.headerNode, 'th $', showsInfo.stage.name);
      }, this);

    },
    
    renderBody: function() {
      // var rb = put(this.bodyNode, 'th $, td.venue $, td.venue $, td.venue $', 'times down this column', 
      //   'stage 1 acts down this column', 'stage 2 acts down this column', 'stage 3 acts down this column');

      put(this.bodyNode, 'th.times'); // TODO: build hour list
      
      var venueLineupNodes = [];
      
      dojo.forEach(this.showData, function(stageLineup) {
        
        // create a single column for all the shows
        var venueLineupNode = put(this.bodyNode, 'td.venue div.artist-lineup');
        
        dojo.forEach(stageLineup.shows, function(setInfo ) {

          var showBox = put(venueLineupNode, 'div.show-box');
          // the show box is sized and placed based on the time information


          var PX_PER_MIN = 2;
          var START_OF_DAY = new Date('09/22/2011 07:00 PM');
          var startOffset = (DD.difference(START_OF_DAY, new Date(setInfo.start), 'minute') * PX_PER_MIN);
          var height = (parseInt(setInfo.length) * PX_PER_MIN) - 1; // shave a pixel off

          console.debug("math... startOffset = %o; height = %o", startOffset, height);
          
          dojo.style(showBox, {
            height: height+'px', // calculate from show length or end time
            top: startOffset+'px'
          });

          put(showBox, 'div.show-container strong.show-title $ +span.show-time $', setInfo.name, setInfo.start)

        }, this);

        venueLineupNodes.push(venueLineupNode);
        
      }, this);
      
      console.debug("venues lineups = %o", venueLineupNodes);
    },
    

    // =====
    
    /*
    var SCHEDULE_DATA =
        [
          {
            stage: {
              name: "My house"
            },
            shows: [
              {
                name: "Good Band",
                start: "12:00pm",
                end: "1:00pm"
              },
              {
                name: "Great Band",
                start: "1:30pm",
                end: "3:15pm"
              },
              {
                name: "Awesome Band",
                start: "4:00pm",
                end: "7:00pm"
              }

            ]
          }
        ];
      */
    
    setEventData: function(data) {
      this.showData = data;
      // render?
      
    }
    
  });
  
});